---
title: "Implementing Apriori Algorithm in R"
output: html_document
---

```{r setup, include=FALSE}

# Limpiamos el entorno de Trabajo
rm(list=ls())

# Limpiamos la consola
cat("\014")

#indicamos el directorio de trabajo
setwd("~/Documentos/R")
```



```{r}
# desargamos y almacenamos en nuestro PC los datos del fichero "Groceries_dataset.csv"
url <- "https://github.com/nupur1492/RProjects/raw/master/MarketBasketAnalysis/Groceries_dataset.csv"
destino <- "./datos/Groceries_dataset.csv"
download.file(url, destino)
dat <- read.csv(destino)
```



```{r pressure, echo=FALSE}
#Implementing Market Basket Analysis using Apriori Algorithm

#read transactions
df_groceries <- read.csv("datos/Groceries_dataset.csv")
str(df_groceries)
```



```{r}
df_sorted <- df_groceries[order(df_groceries$Member_number),]
```



```{r}

#convert member number to numeric
df_sorted$Member_number <- as.numeric(df_sorted$Member_number)
```



```{r}

#convert item description to categorical format

df_sorted$itemDescription <- as.factor(df_sorted$itemDescription)

str(df_sorted)
```



```{r}
#convert dataframe to transaction format using ddply; 

if(sessionInfo()['basePkgs']=="dplyr" | sessionInfo()['otherPkgs']=="dplyr"){
  detach(package:dplyr, unload=TRUE)
}
```



```{r}
#group all the items that were bought together; by the same customer on the same date
library(plyr)
df_itemList <- ddply(df_groceries, c("Member_number","Date"), function(df1)paste(df1$itemDescription,collapse = ","))
```



```{r}
#remove member number and date
df_itemList$Member_number <- NULL
df_itemList$Date <- NULL
```



```{r}
colnames(df_itemList) <- c("itemList")
```



```{r}
#write to csv format
write.csv(df_itemList,"ItemList.csv", quote = FALSE, row.names = TRUE)
```




#-------------------- association rule mining algorithm : apriori -------------------------#




```{r}
#load package required
library(arules)
```



```{r}
#convert csv file to basket format
txn = read.transactions(file="ItemList.csv", rm.duplicates= FALSE, format="basket",sep=",",cols=1);
```



```{r}
#remove quotes from transactions
txn@itemInfo$labels <- gsub("\"","",txn@itemInfo$labels)

```



```{r}
#run apriori algorithm
basket_rules <- apriori(txn,parameter = list(minlen=2,sup = 0.001, conf = 0.01, target="rules"))
#basket_rules <- apriori(txn,parameter = list(minlen=2,sup = 0.00001, conf = 0.01, target="rules"),appearance = list(lhs = "CLEMENTINES")))
```



```{r}
#check if tm is attched; if yes then detach
if(sessionInfo()['basePkgs']=="tm" | sessionInfo()['otherPkgs']=="tm"){
  detach(package:sentiment, unload=TRUE)
  detach(package:tm, unload=TRUE)
}
```



```{r}
#view rules
inspect(basket_rules)
```



```{r}
#convert to datframe and view; optional

df_basket <- as(basket_rules,"data.frame")
df_basket$confidence <- df_basket$confidence * 100
df_basket$support <- df_basket$support * nrow(df_basket)

```



```{r}
# Mining rules for recommendations:

# split lhs and rhs into two columns
library(reshape2)
df_basket <- transform(df_basket, rules = colsplit(rules, pattern = "=>", names = c("lhs","rhs")))
```



```{r}
# Remove curly brackets around rules
df_basket$rules$lhs <- gsub("[[:punct:]]", "", df_basket$rules$lhs)
df_basket$rules$rhs <- gsub("[[:punct:]]", "", df_basket$rules$rhs)
```



```{r}
# convert to chracter
df_basket$rules$lhs <- as.character(df_basket$rules$lhs)
df_basket$rules$rhs <- as.character(df_basket$rules$rhs)
```



```{r}
library(stringi)
library(dplyr)
df_basket$rules %>%
  filter(stri_detect_fixed(lhs, "yogurt")) %>%
  select(rhs)

```



```{r}
# Importamos las librerias a utilizar

packages <- c("arulesViz")
newpack  = packages[!(packages %in% installed.packages()[,"Package"])]

if(length(newpack)) install.packages(newpack)
a=lapply(packages, library, character.only=TRUE)

#plot the rules
# library(arulesViz)
plot(basket_rules, jitter=0)
```



```{r}
set.seed(8000)
plot(basket_rules, method = "grouped", control = list(k = 5))
```



```{r}
plot(basket_rules[1:10,], method="graph", control=list(type="items"))
```



```{r}
plot(basket_rules[1:10,], method="paracoord",  control=list(alpha=.5, reorder=TRUE))
```



```{r}
itemFrequencyPlot(txn, topN = 5)
```



```{r}
plot(basket_rules[1:10,],measure=c("support","lift"), jitter=0 ,shading="confidence", engine='interactive' ,interactive=TRUE)

```


